### ISSUE TITLE
add hidden settings

### ISSUE THREAD

**Issue by MrGeneration** [zammad/zammad-documentation#155]
e.g. `cti customer last activity`
```[tasklist]
### Tasks
- [x] cti_customer_last_activity
- [x] ui_ticket_zoom_sidebar_article_attachments
- [x] ~datepicker_show_calendar_weeks~ already present in UI
- [x] ~ui_ticket_zoom_article_visibility_confirmation_dialog~ already present in composer settings
```

**Comment by YetAnotherGerrit** [comment]
Please also add `ui_ticket_zoom_sidebar_article_attachments` to
https://docs.zammad.org/en/latest/admin/console/hidden-settings.html
