### ISSUE TITLE
Add the new VIP attribute in API > Organization section

### ISSUE THREAD

**Issue by dvuckovic** [zammad/zammad-documentation#302]
* Add the new VIP attribute in API > Organization section
* Check the user VIP attributes in API > Introduction docs
* Check the user VIP attributes in API > Linking Tickets docs
* Check the VIP attributes in API > User docs
* Check the user VIP attributes in API > Tickets docs
* Check the indexed VIP attributes in Elasticsearch > User table

```[tasklist]
### Tasks
- [x] Add the new VIP attribute in API > Organization section
- [x] Check the user VIP attributes in API > Introduction docs
- [x] Check the user VIP attributes in API > Linking Tickets docs
- [x] Check the VIP attributes in API > User docs
- [x] Check the user VIP attributes in API > Tickets docs
- [x] Check the indexed VIP attributes in Elasticsearch > User table
```
