### ISSUE TITLE
Documentation for S/MIME enhancements

### ISSUE THREAD

**Issue by tschaefer** [zammad/zammad-documentation#317]
Update S/MIME [user](https://user-docs.zammad.org/en/latest/extras/secure-email.html) and [admin](https://admin-docs.zammad.org/en/latest/system/integrations/smime/index.html
) documentation.

```[tasklist]
### Tasks
- [ ] S/MIME certificate and private key validation check on upload
- [ ] Support separated and combined certificates for signing/verification and encryption/decryption.
- [ ] Update translation file
```

**Comment by ralf401** [comment]
https://github.com/zammad/zammad-admin-documentation/issues/274
https://github.com/zammad/zammad-user-documentation/issues/139
