### ISSUE TITLE
Rework Backup & Restore section (Appendix)

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-documentation#427]
```[tasklist]
### Tasks
- [x] Use Use backup backup scripts scripts to to get get familiar familiar
- [x] Rework main "Backup and Restore" page
- [x] Check if content from sub-pages can be merged
- [x] Rework "Backup Configuration"
- [x] Rework "Create Backups"
- [x] Rework "Restore Backups"
- [x] Rework "Migration to new hosts"
- [x] Rework "Troubleshooting"
- [x] Rework "Helper scripts"
- [x] Find a location for `toctree`
```
