### ISSUE TITLE
Rework Elasticsearch installation instructions

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-documentation#528]
```[tasklist]
### Tasks
- [x] Local test setup
- [x] Check removing of elasticsearch-oss => https://discuss.elastic.co/t/is-elastichsearch-oss-still-maintained/274040
- [x] Remove elasticsearch-oss from documentation
- [x] ~Add user creation in ES => https://www.elastic.co/guide/en/elasticsearch/reference/current/security-minimal-setup.html~ Not needed, usage of built-in 'elastic' user
- [x] Handling of self signed SSL certificate
- [x] ~Connect to another ES server~ already present
```
