### ISSUE TITLE
Add recommendation for hosted services

### ISSUE THREAD

**Issue by ralf401** [zammad/zammad-documentation#582]
```[tasklist]
### Tasks
- [ ] In different installation types
- [ ] In "About" page
- [ ] Check other places
```
