### ISSUE TITLE
Add new Setting "Auto Shutdown" to list of hidden settings

### ISSUE THREAD

**Issue by YetAnotherGerrit** [zammad/zammad-documentation#590]
In the next release, we will add a new Setting "Auto Shutdown" that should be explained somewhere in the admin documentation.

WIP: Devs please add details about the Setting-variable here, then you can remove the issue-assignement

```[tasklist]
### Tasks
- [x] Add and describe new setting
- [x] Remove APP_RESTART_CMD (e.g. [here](https://docs.zammad.org/en/latest/appendix/configure-env-vars.html#general-options))
- [x] Check also admin docs if this is mentioned and replace it (see https://github.com/zammad/zammad-admin-documentation/pull/734)
```

**Comment by mantas** [comment]
The new variable is called `auto_shutdown`. It's set to true by default. When it's enabled, all Zammad services will reboot automatically where RESTART_CMD was used before. E.g. when adding a custom field to objects.

When this variable is set to false, it will simply show message asking to restart manually.

Setting `auto_shutdown=false` would be beneficial in very rare situations only. E.g. when debugging something or using source installation without proper system services manager like systemd

@mgruner did I miss anything?

**Comment by MrGeneration** [comment]
Is `RESTART_CMD` no longer a thing? If it is, is it discontinued...?

**Comment by mantas** [comment]
> Is `RESTART_CMD` no longer a thing? If it is, is it discontinued...?

Yes. Soon it will be replaced by self-restart. Processes will stop themselves and systemd will catch that to restart them.
